In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [3]:
iris = pd.read_csv('./iris.csv')

In [4]:
iris_data = iris.iloc[:, 0:4].values
iris_target = iris.iloc[:, 4].values

In [5]:
# As classes devem ser representadas por 3 numeros int (0 ou 1) para as colunas setosa, virginica e versicolor
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
labelencoder = LabelEncoder()
indexes = labelencoder.fit_transform(iris_target)
categories = to_categorical(indexes)

In [6]:
# 0 setosa
# 1 virginica
# 2 versicolor
print(indexes)
# 1 0 0 setosa
# 0 1 0 virginica
# 0 0 1 versicolor
print(categories)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

In [7]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris_data, categories, test_size=0.30)

## Parâmetros importantes (https://keras.io/api/)
- input_dim : quantidade de atributos de entrada. Aparece apenas na primeira camada 
- units : neuronios de cada entrada
- activation : função de ativação, vários tipos para camadas intermediarias. softmax na ultima camada para classificação de 3 ou mais classes. Em classificação binária, usar um neuronio (units=1) na última camada com função sigmoid
- optimizer : testar mais de um, pode iniciar com adam
- loss : categorical_crossentropy para mais 3 ou mais classes, binary_entropy para classificação binária
- metrics : categorical_accuracy pode ser usada para 3 ou mais classes e binary_accuracy para classificação binária
- mas há outras métricas

In [8]:
from tensorflow.keras.models import Sequential # Estrutura de rede
from tensorflow.keras.layers import Dense      # camadas densas

classifier = Sequential()
# Tamanho da primeira camada (<entradas> + <saidas>) /2 = (4 + 3)/2 = 3.5 --> 4 (arredonda pra cima) 
classifier.add(Dense(units=4, activation='relu', input_dim=4)) #input_dim = número de atributos

# units = 3 para 3 classes
classifier.add(Dense(units=3, activation='softmax')) # softmax para 3 ou mais classes

classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

classifier.fit(data_train, target_train, batch_size=10, epochs=500)


Epoch 1/500
11/11 [==============================] - 0s 510us/step - loss: 2.0513 - categorical_accuracy: 0.3429
Epoch 2/500
11/11 [==============================] - 0s 422us/step - loss: 1.8789 - categorical_accuracy: 0.3429
Epoch 3/500
11/11 [==============================] - 0s 413us/step - loss: 1.7275 - categorical_accuracy: 0.3429
Epoch 4/500
11/11 [==============================] - 0s 455us/step - loss: 1.6012 - categorical_accuracy: 0.3429
Epoch 5/500
11/11 [==============================] - 0s 419us/step - loss: 1.5061 - categorical_accuracy: 0.3429
Epoch 6/500
11/11 [==============================] - 0s 444us/step - loss: 1.4171 - categorical_accuracy: 0.3429
Epoch 7/500
11/11 [==============================] - 0s 392us/step - loss: 1.3507 - categorical_accuracy: 0.3429
Epoch 8/500
11/11 [==============================] - 0s 426us/step - loss: 1.2928 - categorical_accuracy: 0.3429
Epoch 9/500
11/11 [==============================] - 0s 334us/step - loss: 1.2456 - categorical_

Epoch 73/500
11/11 [==============================] - 0s 343us/step - loss: 0.7198 - categorical_accuracy: 0.6571
Epoch 74/500
11/11 [==============================] - 0s 356us/step - loss: 0.7167 - categorical_accuracy: 0.6571
Epoch 75/500
11/11 [==============================] - 0s 365us/step - loss: 0.7136 - categorical_accuracy: 0.6571
Epoch 76/500
11/11 [==============================] - 0s 343us/step - loss: 0.7103 - categorical_accuracy: 0.6571
Epoch 77/500
11/11 [==============================] - 0s 347us/step - loss: 0.7072 - categorical_accuracy: 0.6571
Epoch 78/500
11/11 [==============================] - 0s 352us/step - loss: 0.7042 - categorical_accuracy: 0.6571
Epoch 79/500
11/11 [==============================] - 0s 331us/step - loss: 0.7010 - categorical_accuracy: 0.6571
Epoch 80/500
11/11 [==============================] - 0s 330us/step - loss: 0.6982 - categorical_accuracy: 0.6571
Epoch 81/500
11/11 [==============================] - 0s 386us/step - loss: 0.6953 - cat

11/11 [==============================] - 0s 338us/step - loss: 0.5640 - categorical_accuracy: 0.6667
Epoch 145/500
11/11 [==============================] - 0s 346us/step - loss: 0.5620 - categorical_accuracy: 0.6857
Epoch 146/500
11/11 [==============================] - 0s 367us/step - loss: 0.5606 - categorical_accuracy: 0.6857
Epoch 147/500
11/11 [==============================] - 0s 344us/step - loss: 0.5592 - categorical_accuracy: 0.6857
Epoch 148/500
11/11 [==============================] - 0s 339us/step - loss: 0.5577 - categorical_accuracy: 0.6857
Epoch 149/500
11/11 [==============================] - 0s 363us/step - loss: 0.5565 - categorical_accuracy: 0.6857
Epoch 150/500
11/11 [==============================] - 0s 327us/step - loss: 0.5550 - categorical_accuracy: 0.6952
Epoch 151/500
11/11 [==============================] - 0s 332us/step - loss: 0.5536 - categorical_accuracy: 0.6952
Epoch 152/500
11/11 [==============================] - 0s 355us/step - loss: 0.5523 - categori

11/11 [==============================] - 0s 339us/step - loss: 0.4863 - categorical_accuracy: 0.8190
Epoch 216/500
11/11 [==============================] - 0s 351us/step - loss: 0.4858 - categorical_accuracy: 0.8000
Epoch 217/500
11/11 [==============================] - 0s 335us/step - loss: 0.4847 - categorical_accuracy: 0.7905
Epoch 218/500
11/11 [==============================] - 0s 344us/step - loss: 0.4837 - categorical_accuracy: 0.8190
Epoch 219/500
11/11 [==============================] - 0s 427us/step - loss: 0.4831 - categorical_accuracy: 0.8286
Epoch 220/500
11/11 [==============================] - 0s 358us/step - loss: 0.4824 - categorical_accuracy: 0.8286
Epoch 221/500
11/11 [==============================] - 0s 329us/step - loss: 0.4814 - categorical_accuracy: 0.8286
Epoch 222/500
11/11 [==============================] - 0s 329us/step - loss: 0.4807 - categorical_accuracy: 0.8095
Epoch 223/500
11/11 [==============================] - 0s 362us/step - loss: 0.4800 - categori

11/11 [==============================] - 0s 335us/step - loss: 0.4358 - categorical_accuracy: 0.8762
Epoch 287/500
11/11 [==============================] - 0s 349us/step - loss: 0.4351 - categorical_accuracy: 0.8857
Epoch 288/500
11/11 [==============================] - 0s 351us/step - loss: 0.4345 - categorical_accuracy: 0.9048
Epoch 289/500
11/11 [==============================] - 0s 327us/step - loss: 0.4341 - categorical_accuracy: 0.9048
Epoch 290/500
11/11 [==============================] - 0s 340us/step - loss: 0.4333 - categorical_accuracy: 0.9048
Epoch 291/500
11/11 [==============================] - 0s 358us/step - loss: 0.4327 - categorical_accuracy: 0.8952
Epoch 292/500
11/11 [==============================] - 0s 340us/step - loss: 0.4319 - categorical_accuracy: 0.9048
Epoch 293/500
11/11 [==============================] - 0s 335us/step - loss: 0.4313 - categorical_accuracy: 0.9048
Epoch 294/500
11/11 [==============================] - 0s 355us/step - loss: 0.4307 - categori

11/11 [==============================] - 0s 340us/step - loss: 0.3900 - categorical_accuracy: 0.9238
Epoch 358/500
11/11 [==============================] - 0s 341us/step - loss: 0.3895 - categorical_accuracy: 0.9238
Epoch 359/500
11/11 [==============================] - 0s 351us/step - loss: 0.3886 - categorical_accuracy: 0.9238
Epoch 360/500
11/11 [==============================] - 0s 327us/step - loss: 0.3881 - categorical_accuracy: 0.9238
Epoch 361/500
11/11 [==============================] - 0s 335us/step - loss: 0.3878 - categorical_accuracy: 0.9238
Epoch 362/500
11/11 [==============================] - 0s 355us/step - loss: 0.3866 - categorical_accuracy: 0.9238
Epoch 363/500
11/11 [==============================] - 0s 317us/step - loss: 0.3863 - categorical_accuracy: 0.9238
Epoch 364/500
11/11 [==============================] - 0s 332us/step - loss: 0.3855 - categorical_accuracy: 0.9238
Epoch 365/500
11/11 [==============================] - 0s 301us/step - loss: 0.3847 - categori

11/11 [==============================] - 0s 377us/step - loss: 0.3428 - categorical_accuracy: 0.9524
Epoch 429/500
11/11 [==============================] - 0s 341us/step - loss: 0.3421 - categorical_accuracy: 0.9524
Epoch 430/500
11/11 [==============================] - 0s 316us/step - loss: 0.3412 - categorical_accuracy: 0.9524
Epoch 431/500
11/11 [==============================] - 0s 359us/step - loss: 0.3413 - categorical_accuracy: 0.9333
Epoch 432/500
11/11 [==============================] - 0s 328us/step - loss: 0.3400 - categorical_accuracy: 0.9238
Epoch 433/500
11/11 [==============================] - 0s 321us/step - loss: 0.3392 - categorical_accuracy: 0.9333
Epoch 434/500
11/11 [==============================] - 0s 367us/step - loss: 0.3387 - categorical_accuracy: 0.9333
Epoch 435/500
11/11 [==============================] - 0s 345us/step - loss: 0.3379 - categorical_accuracy: 0.9524
Epoch 436/500
11/11 [==============================] - 0s 367us/step - loss: 0.3373 - categori

11/11 [==============================] - 0s 358us/step - loss: 0.2967 - categorical_accuracy: 0.9619
Epoch 500/500
11/11 [==============================] - 0s 343us/step - loss: 0.2957 - categorical_accuracy: 0.9619


In [9]:
predictions = classifier.predict(data_test)

print(predictions)

2/2 [==============================] - 0s 853us/step
[[4.7127670e-03 6.3450092e-01 3.6078626e-01]
 [1.4528717e-05 3.2802096e-01 6.7196453e-01]
 [1.2655896e-01 6.9573569e-01 1.7770524e-01]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [3.9304877e-04 5.0039935e-01 4.9920756e-01]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [1.2708662e-06 2.2563009e-01 7.7436858e-01]
 [3.2887775e-03 6.1615705e-01 3.8055414e-01]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [1.7201508e-05 3.3604953e-01 6.6393322e-01]
 [1.4727282e-04 4.4646239e-01 5.5339032e-01]
 [1.0488355e-02 6.7212331e-01 3.1738830e-01]
 [1.9301569e-04 4.6120024e-01 5.3860670e-01]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [1.6564226e-06 2.3549162e-01 7.6450670e-01]
 [2.3577630e-07 1.8519597e-01 8.1480378e-01]
 [9.3509287e-01 5.9886731e-02 5.0203647e-03]
 [6.0290736e-06 2.8807995e-01 7.1191400e-01]
 [1.4821117e-07 1.5706882e-01 8.4293103e-01]
 [

In [10]:
# Transforma em true scores maiores que 0.5 e em false scores menores ou iguais a 0.5
predictions = (predictions > 0.5)

import numpy as np
# retorna o indice (0,1 ou 2) com maior score para cada instancia das das classes alvo (gabarito) e das predições
target_test_index = [np.argmax(t) for t in target_test] 
predictions_index = [np.argmax(t) for t in predictions]

print(target_test_index)

[1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 2, 0, 1, 2, 0, 1, 0]


In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(target_test_index, predictions_index))

1.0


In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(target_test_index, predictions_index))

[[14  0  0]
 [ 0 14  0]
 [ 0  0 17]]


In [13]:
from sklearn.metrics import classification_report
print(classification_report(target_test_index, predictions_index))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        17

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Validação Cruzada (Cross Validation)

In [14]:
from tensorflow.keras.models import Sequential # Estrutura de rede
from tensorflow.keras.layers import Dense      # camadas densas
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np


def get_classifier():
    classifier = Sequential()
    # Tamanho da primeira camada (<entradas> + <saidas>) /2 = (4 + 3)/2 = 3.5 --> 4 (arredonda pra cima) 
    classifier.add(Dense(units=4, activation='relu', input_dim=4)) #input_dim = número de atributos

    # units = 3 para 3 classes
    classifier.add(Dense(units=3, activation='softmax')) # softmax para 3 ou mais classes

    classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
    
    return classifier


kfold = KFold(n_splits=10, shuffle=True)

accuracies = []

# utiliza o dataset inteiro iris_data (atributos) e categories (classes)
for train_index, test_index in kfold.split(iris_data):
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = categories[train_index], categories[test_index]

    model = get_classifier()
    model.fit(x=X_train, y=y_train, batch_size=10, epochs=500, verbose=0)

    y_pred = model.predict(X_test)
    
    predictions = (y_pred > 0.5)

    # retorna o indice (0,1 ou 2) com maior score para cada instancia das das classes alvo (gabarito) e das predições
    target_test_index = [np.argmax(t) for t in y_test] 
    predictions_index = [np.argmax(t) for t in predictions]

    accuracy = accuracy_score(target_test_index, predictions_index)
    accuracies.append(accuracy)
    print(f'Accuracy: {accuracy}')

print('Accuracia Média', np.mean(accuracies))



1/1 [==============================] - 0s 13ms/step
Accuracy: 0.9333333333333333
1/1 [==============================] - 0s 13ms/step
Accuracy: 0.9333333333333333
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
1/1 [==============================] - 0s 13ms/step
Accuracy: 0.9333333333333333
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
1/1 [==============================] - 0s 13ms/step
Accuracy: 0.9333333333333333
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
1/1 [==============================] - 0s 13ms/step
Accuracy: 1.0
Accuracia Média 0.9733333333333334
